name = "terabox-web"  # 你的 project 名稱
compatibility_date = "2025-12-24"  # 今天或更晚
compatibility_flags = ["nodejs_compat"]

main = ".open-next/server-functions/index.mjs"  # 或 ".open-next/worker.js"，build 後確認 .open-next 裡的檔
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "COOKIE_KV"
id = "6f04acc9b12148e28dfd23bb04edba5a"  # 你的 KV ID
# 如果需要 preview_id（本地測試用），可以加一個不同的 namespace ID
# preview_id = "另一個 preview KV ID"